# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

stages:
- stage: Build
  jobs:
  - job:
    displayName: "build"
    timeoutInMinutes: 60

    pool:
      vmImage: ubuntu-20.04

    steps:
    - script: |
        sudo rm -rf $(ls -A1)
      displayName: 'Clean Workspace'

    - script: |
        sudo apt-get update
        sudo apt-get install -y quilt build-essential debhelper bc
      displayName: 'Init'

    - checkout: self
      clean: true
      submodules: recursive
      displayName: 'Checkout code'

    - script: |
        make
        cp *.deb $(Build.ArtifactStagingDirectory)/
      displayName: "Build"
    - publish: $(Build.ArtifactStagingDirectory)/
      artifact: openssl
      displayName: "Archive artifacts"
